/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import Dao.NhanVienDao;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
//import jdk.jfr.internal.instrument.JDKEvents;
import main.Quanlithuvien;
import utils.Auth;
import utils.MsgBox;

/**
 *
 * @author duyvo
 */
public class DoiMatKhau extends javax.swing.JFrame {

	NhanVienDao dao = new NhanVienDao();
	String Mes = "";

	/**
	 * Creates new form Login_A
	 */
	public DoiMatKhau() {
		initComponents();
		init();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		panelBorder1 = new swing.menu.PanelBorder();
		txtMKMoi = new button.JPassword.PasswordField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		btnDoimatkhua = new button.MyButton();
		btnHuy = new button.MyButton();
		txtNhapLaiMK = new button.JPassword.PasswordField();
		jLabel4 = new javax.swing.JLabel();
		txtMKcu = new button.JPassword.PasswordField();
		jLabel5 = new javax.swing.JLabel();
		txttendangnhap = new button.textfield.TextField();
		menu_11 = new component.menu_1();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setUndecorated(true);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));
		jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED,
				new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 51),
				new java.awt.Color(255, 102, 102)));

		panelBorder1.setBackground(new java.awt.Color(255, 204, 204));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel1.setText("Mật khẩu cũ:");

		jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel2.setText("Mật khẩu mới:");

		btnDoimatkhua.setText("Đổi mật khẩu");
		btnDoimatkhua.setRadius(12);
		btnDoimatkhua.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDoimatkhuaActionPerformed(evt);
			}
		});

		btnHuy.setText("Hủy");
		btnHuy.setRadius(12);
		btnHuy.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHuyActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel4.setText("Nhập lại mật khẩu:");

		jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel5.setText("Tên Đăng Nhập");

		txttendangnhap.setEditable(false);
		txttendangnhap.setEnabled(false);
		txttendangnhap.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txttendangnhapActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
		panelBorder1.setLayout(panelBorder1Layout);
		panelBorder1Layout.setHorizontalGroup(panelBorder1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
						.addContainerGap(21, Short.MAX_VALUE)
						.addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(panelBorder1Layout.createSequentialGroup().addComponent(jLabel5)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(txttendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 355,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(panelBorder1Layout.createSequentialGroup()
										.addGroup(panelBorder1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel2).addComponent(jLabel1).addComponent(jLabel4))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(panelBorder1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout
														.createSequentialGroup()
														.addComponent(btnDoimatkhua,
																javax.swing.GroupLayout.PREFERRED_SIZE, 102,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE,
																102, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(txtNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE, 355,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txtMKcu, javax.swing.GroupLayout.PREFERRED_SIZE, 355,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 355,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGap(104, 104, 104)));
		panelBorder1Layout.setVerticalGroup(panelBorder1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
						.addContainerGap(12, Short.MAX_VALUE)
						.addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txttendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(txtMKcu, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2).addComponent(txtMKMoi, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtNhapLaiMK, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4))
						.addGap(18, 18, 18)
						.addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnDoimatkhua, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(22, 22, 22)));

		jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(255, 255, 255));
		jLabel3.setText("Đổi mật khẩu");

		javax.swing.GroupLayout menu_11Layout = new javax.swing.GroupLayout(menu_11);
		menu_11.setLayout(menu_11Layout);
		menu_11Layout.setHorizontalGroup(menu_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(menu_11Layout.createSequentialGroup().addGap(285, 285, 285).addComponent(jLabel3)
						.addContainerGap(306, Short.MAX_VALUE)));
		menu_11Layout.setVerticalGroup(menu_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(menu_11Layout.createSequentialGroup().addContainerGap().addComponent(jLabel3)
						.addContainerGap(14, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(menu_11, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(44, 44, 44)
						.addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(menu_11, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHuyActionPerformed
		try {
			// TODO add your handling code here:
			cancel();
		} catch (SQLException ex) {
			Logger.getLogger(DoiMatKhau.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_btnHuyActionPerformed

	private void btnDoimatkhuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDoimatkhuaActionPerformed
		// System.out.println("da chay ");
		changePassword();
	}// GEN-LAST:event_btnDoimatkhuaActionPerformed

	private void txttendangnhapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txttendangnhapActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txttendangnhapActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DoiMatKhau().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private button.MyButton btnDoimatkhua;
	private button.MyButton btnHuy;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private component.menu_1 menu_11;
	private swing.menu.PanelBorder panelBorder1;
	private button.JPassword.PasswordField txtMKMoi;
	private button.JPassword.PasswordField txtMKcu;
	private button.JPassword.PasswordField txtNhapLaiMK;
	private button.textfield.TextField txttendangnhap;

	// End of variables declaration//GEN-END:variables
	private void init() {
		this.setLocationRelativeTo(null);
		if (Auth.user != null) {
			Auth.user.getMaNV();
		}
		txttendangnhap.setText(Auth.user.getMaNV());
	}

	;

	private boolean changePassword() {
		if (Auth.user != null) {
			Auth.user.getMaNV();
		}
//       String manv = txttendangnhap.getText();
		String mk = new String(txtMKcu.getPassword());
		String MKMoi = new String(txtMKMoi.getPassword());
		String NhapMKMoi = new String(txtNhapLaiMK.getPassword());
//        if (!Auth.user.getMaNV().equalsIgnoreCase(Auth.user.getMaNV())) {
//            MsgBox.alert(this, "Sai tên đăng nhập!");
//        } else 

		// mật khẩu
		if (mk.equals("")) {
			Mes = "Không được để trống mật khẩu";
			MsgBox.alert(this, Mes);
			return false;
		}
		if (!mk.equals(Auth.user.getMatKhau())) {
			Mes = "Sai mật khẩu!";
			MsgBox.alert(this, Mes);
			return false;
		}
		// mật khẩu mới
		if (MKMoi.equals("")) {
			Mes = "Không được để trống mật khẩu mới";
			MsgBox.alert(this, Mes );
			return false;
		}
		if (MKMoi.equals(mk)) {
			Mes = "Mật khẩu trùng mật khẩu gốc!";
			MsgBox.alert(this, Mes );
			return false;

		}
		// Nhập lại mật khẩu mới
		if (NhapMKMoi.equals("")) {
			Mes = "Không được để trống xác nhận mật khẩu";
			MsgBox.alert(this, Mes);
			return false;
		}
		if (!MKMoi.equals(NhapMKMoi)) {
			Mes = "Mật khẩu mới không trùng!";
			MsgBox.alert(this, Mes);
			return false;
		}
		Auth.user.setMatKhau(MKMoi);
		dao.update(Auth.user);
		Mes = "Đổi mật khẩu thành công";
		MsgBox.alert(this, "Đổi mật khẩu thành công");
		this.dispose();
		Login lg = new Login();
		lg.setVisible(rootPaneCheckingEnabled);
		return true;

	}

	private void cancel() throws SQLException {
		this.dispose();
		Quanlithuvien tv = new Quanlithuvien();
		tv.setVisible(rootPaneCheckingEnabled);
	}

	public NhanVienDao getDao() {
		return dao;
	}

	public void setDao(NhanVienDao dao) {
		this.dao = dao;
	}

	public button.MyButton getBtnDoimatkhua() {
		return btnDoimatkhua;
	}

	public void setBtnDoimatkhua(button.MyButton btnDoimatkhua) {
		this.btnDoimatkhua = btnDoimatkhua;
	}

	public button.MyButton getBtnHuy() {
		return btnHuy;
	}

	public void setBtnHuy(button.MyButton btnHuy) {
		this.btnHuy = btnHuy;
	}

	public javax.swing.JLabel getjLabel1() {
		return jLabel1;
	}

	public void setjLabel1(javax.swing.JLabel jLabel1) {
		this.jLabel1 = jLabel1;
	}

	public javax.swing.JLabel getjLabel2() {
		return jLabel2;
	}

	public void setjLabel2(javax.swing.JLabel jLabel2) {
		this.jLabel2 = jLabel2;
	}

	public javax.swing.JLabel getjLabel3() {
		return jLabel3;
	}

	public void setjLabel3(javax.swing.JLabel jLabel3) {
		this.jLabel3 = jLabel3;
	}

	public javax.swing.JLabel getjLabel4() {
		return jLabel4;
	}

	public void setjLabel4(javax.swing.JLabel jLabel4) {
		this.jLabel4 = jLabel4;
	}

	public javax.swing.JLabel getjLabel5() {
		return jLabel5;
	}

	public void setjLabel5(javax.swing.JLabel jLabel5) {
		this.jLabel5 = jLabel5;
	}

	public javax.swing.JPanel getjPanel1() {
		return jPanel1;
	}

	public void setjPanel1(javax.swing.JPanel jPanel1) {
		this.jPanel1 = jPanel1;
	}

	public component.menu_1 getMenu_11() {
		return menu_11;
	}

	public void setMenu_11(component.menu_1 menu_11) {
		this.menu_11 = menu_11;
	}

	public swing.menu.PanelBorder getPanelBorder1() {
		return panelBorder1;
	}

	public void setPanelBorder1(swing.menu.PanelBorder panelBorder1) {
		this.panelBorder1 = panelBorder1;
	}

	public button.JPassword.PasswordField getTxtMKMoi() {
		return txtMKMoi;
	}

	public void setTxtMKMoi(button.JPassword.PasswordField txtMKMoi) {
		this.txtMKMoi = txtMKMoi;
	}

	public button.JPassword.PasswordField getTxtMKcu() {
		return txtMKcu;
	}

	public void setTxtMKcu(button.JPassword.PasswordField txtMKcu) {
		this.txtMKcu = txtMKcu;
	}

	public button.JPassword.PasswordField getTxtNhapLaiMK() {
		return txtNhapLaiMK;
	}

	public void setTxtNhapLaiMK(button.JPassword.PasswordField txtNhapLaiMK) {
		this.txtNhapLaiMK = txtNhapLaiMK;
	}

	public button.textfield.TextField getTxttendangnhap() {
		return txttendangnhap;
	}

	public void setTxttendangnhap(button.textfield.TextField txttendangnhap) {
		this.txttendangnhap = txttendangnhap;
	}

	public String getMes() {
		return Mes;
	}

	public void setMes(String mes) {
		Mes = mes;
	}

}
