/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import utils.MsgBox;
import Dao.NXBDao;
import Entity.NXB;

/**
 *
 * @author duyvo
 */
public class NhaXuatBan extends javax.swing.JFrame {
NXBDao nxbdao= new NXBDao();
   int row = 0;
    /**
     * Creates new form NXBq
     */
    public NhaXuatBan() {
        initComponents();
        init();
        tblNXB.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        menu_11 = new component.menu_1();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelBorder1 = new swing.menu.PanelBorder();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaNXB = new button.textfield.TextField();
        lblOTP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNXB = new javax.swing.JTable();
        myButton2 = new button.MyButton();
        myButton4 = new button.MyButton();
        myButton3 = new button.MyButton();
        myButton1 = new button.MyButton();
        txtTenNXB = new button.textfield.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nhà xuất bản");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menu_11Layout = new javax.swing.GroupLayout(menu_11);
        menu_11.setLayout(menu_11Layout);
        menu_11Layout.setHorizontalGroup(
            menu_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_11Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(19, 19, 19))
        );
        menu_11Layout.setVerticalGroup(
            menu_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelBorder1.setBackground(new java.awt.Color(255, 204, 204));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mã NXB:");
        panelBorder1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên NXB:");
        panelBorder1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtMaNXB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaNXBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaNXBFocusLost(evt);
            }
        });
        txtMaNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNXBActionPerformed(evt);
            }
        });
        panelBorder1.add(txtMaNXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 132, -1));

        lblOTP.setBackground(new java.awt.Color(255, 204, 204));
        lblOTP.setForeground(new java.awt.Color(255, 204, 204));
        panelBorder1.add(lblOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tblNXB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã NXB", "Tên NXB"
            }
        ));
        tblNXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNXBMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblNXBMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblNXB);

        panelBorder1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 411, 188));

        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-x.png"))); // NOI18N
        myButton2.setRadius(10);
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        panelBorder1.add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 210, 50, 45));

        myButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bxs-news.png"))); // NOI18N
        myButton4.setRadius(10);
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton4ActionPerformed(evt);
            }
        });
        panelBorder1.add(myButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 210, 50, 45));

        myButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-pencil.png"))); // NOI18N
        myButton3.setRadius(10);
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        panelBorder1.add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 210, 50, 45));

        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bx-plus.png"))); // NOI18N
        myButton1.setColorClick(new java.awt.Color(255, 204, 153));
        myButton1.setRadius(10);
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        panelBorder1.add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 210, 50, 45));

        txtTenNXB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenNXBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenNXBFocusLost(evt);
            }
        });
        txtTenNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNXBActionPerformed(evt);
            }
        });
        panelBorder1.add(txtTenNXB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 132, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                    .addComponent(menu_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(menu_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNXBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaNXBFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNXBFocusGained

    private void txtMaNXBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaNXBFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNXBFocusLost

    private void txtMaNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNXBActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
         delete();
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed
         clear1();
    }//GEN-LAST:event_myButton4ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
          update();
    }//GEN-LAST:event_myButton3ActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed

            insert();
    }//GEN-LAST:event_myButton1ActionPerformed

    private void tblNXBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNXBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblNXBMouseClicked

    private void tblNXBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNXBMousePressed
        if (evt.getClickCount() == 2) {
            this.row = tblNXB.getSelectedRow();
            this.edit();
//            clearValidate();
        }
    }//GEN-LAST:event_tblNXBMousePressed

    private void txtTenNXBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenNXBFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNXBFocusGained

    private void txtTenNXBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenNXBFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNXBFocusLost

    private void txtTenNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNXBActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NXB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NXB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NXB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NXB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhaXuatBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOTP;
    private component.menu_1 menu_11;
    private button.MyButton myButton1;
    private button.MyButton myButton2;
    private button.MyButton myButton3;
    private button.MyButton myButton4;
    private swing.menu.PanelBorder panelBorder1;
    private javax.swing.JTable tblNXB;
    private button.textfield.TextField txtMaNXB;
    private button.textfield.TextField txtTenNXB;
    // End of variables declaration//GEN-END:variables

 public void init() {
//        new Timer(1000, new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                Date now = new Date();
//                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
//                String text = formater.format(now);
//
////                lblDongHo.setText(text);
//            }
//        }).start();
        this.fillTable();
        this.setLocationRelativeTo(null);

//        this.updateStatus();
    }
 
 private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblNXB.getModel();
        model.setRowCount(0);
        try {
            List<NXB> list = nxbdao.selectAll();
                    
            for (NXB nv : list) {
                Object[] row = {
                    nv.getMaNXB(),
                    nv.getTenNXB(),
                    };
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu nhân viên!");
            e.printStackTrace();
        }
    }
 
 
 
 
   private void insert() {
//        if (validateInsert() == true) {
            NXB it = this.getForm();

            try {
                nxbdao.insert(it); // thêm mới
                this.fillTable(); // đỗ lại bảng
                this.clear1(); // xóa trắng form
                JOptionPane.showMessageDialog(this, "Thêm nhân viên mới thành công!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Thêm nhân viên mới thất bại!");
                e.printStackTrace();

            }
//        }
    }

    private void update() {
//        if (validateEdit()) {

//            NhanVien nv = this.getForm();
            NXB it = this.getForm();

            try {
                nxbdao.update(it); // cập nhật
                this.fillTable(); // đổ lại bảng
                JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thất bại!");
                e.printStackTrace();
            }
        

    }

    private void delete() {

        String manv = txtMaNXB.getText();
        if (MsgBox.confirm(this, "Bạn có thực sự muốn xóa nhân viên này không?")) {
            try {
                nxbdao.delete(manv);
                this.fillTable();
                this.clear1();
                MsgBox.alert(this, "Xóa nhân viên thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa nhân viên thất bại!");
                e.printStackTrace();
            }
        }

    }
    
    private void clear1() {
        txtMaNXB.setText("");
        txtTenNXB.setText("");
       
    }


      private void setForm(NXB it) {
        txtMaNXB.setText(it.getMaNXB());
        txtTenNXB.setText(it.getTenNXB());

        

    }

    private NXB getForm() {
        NXB nv = new NXB();
        nv.setMaNXB(txtMaNXB.getText());
        nv.setTenNXB(txtTenNXB.getText());
        

        return nv;
    }
    
       private void edit() {
        try {
            String manv = (String) tblNXB.getValueAt(this.row, 0);
            NXB nv = nxbdao.selectById(manv);
            if (nv != null) {
                this.setForm(nv);
//                jTabbedPane1.setSelectedIndex(0);
//                this.updateStatus();
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
